### ISSUE TITLE
Spack install fails with 'unsatisfiable version constraint'

### ISSUE THREAD

**Issue by BenWibking** [LLNL/STAT#14]
I'm not sure if this should be reported here, or in the Spack repository, but here it is for now.

I get this error when running `./bin/spack install stat`:

```
[bw0729@gadi-login-04 spack]$ ./bin/spack install stat
==> Warning: gcc@8.2.1 cannot build optimized binaries for "cascadelake". Using best target possible: "skylake_avx512"
==> Error: An unsatisfiable version constraint has been detected for spec:

    boost@1.70.0%gcc@8.2.1+atomic+chrono~clanglibcpp~context~coroutine cxxstd=98 +date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout visibility=hidden +wave arch=linux-centos8-skylake_avx512


while trying to concretize the partial spec:

    dyninst@:9.99
        ^cmake@2.8:


dyninst requires boost version 1.61.0:1.69.99, but spec asked for 1.70.0
```

**Comment by lee218llnl** [comment]
Can you try running `./bin/spack install stat^boost@1.69.0`

**Comment by lee218llnl** [comment]
You may actually need to run `./bin/spack install stat^boost@1.69.0^gettext~libxml2` if you get an error, "python requires gettext variant ~libxml2, but spec asked for +libxml2" from my previous command.

**Comment by BenWibking** [comment]
That fixes the version constraint, but I now get a build error when compiling Dyninst. I've attached the spack-build-out.txt file.
[spack-build-out.txt](https://github.com/LLNL/STAT/files/4142469/spack-build-out.txt)

**Comment by lee218llnl** [comment]
It looks like that is a known bug in Dyninst 9 that has since been fixed. This appears to work for me: `./bin/spack install --keep-stage stat@develop^dyninst@10.1.0^gettext~libxml2`. Can you please try that?

**Comment by BenWibking** [comment]
That has fixed that issue, but now I get a build error with STAT itself:

``
==> Installing stat
==> Searching for binary cache of stat
==> No binary for stat found: installing from source
==> Cloning git repository: https://github.com/llnl/stat.git on branch develop
==> No checksum needed when fetching with git
==> Already staged spack-stage-stat-develop-qq5gh3c6nzuedcq4iwnrtjt4txcchzb6 in /scratch/jh2/bw0729/tmp/spack-stage/spack-stage-stat-develop-qq5gh3c6nzuedcq4iwnrtjt4txcchzb6
==> No patches needed for stat
==> Building stat [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/scratch/jh2/bw0729/tmp/spack-stage/spack-stage-stat-develop-qq5gh3c6nzuedcq4iwnrtjt4txcchzb6/spack-src/configure' '--prefix=/g/data/jh2/bw0729/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.2.1/stat-develop-qq5gh3c6nzuedcq4iwnrtjt4txcchzb6' '--with-launchmon=/g/data/jh2/bw0729/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.2.1/launchmon-1.0.2-643fntbfrs7crquspy7khappyupbexno' '--with-mrnet=/g/data/jh2/bw0729/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.2.1/mrnet-5.0.1-3-el3k3c7dbfewq2e2qth3dlhhijfvimwp' '--with-graphlib=/g/data/jh2/bw0729/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.2.1/graphlib-3.0.0-rbrmgnwliml3utt5hwcwbvt2bhfigjqy' '--with-stackwalker=/g/data/jh2/bw0729/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.2.1/dyninst-10.1.0-ryvqjltigqxxfn64q5fvlqpnhs6qjlxj' '--with-python=/g/data/jh2/bw0729/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.2.1/python-3.7.6-blzhnoz7vo5vrkoku4y57cgqsiic7veh/bin/python3.7' '--with-boost=/g/data/jh2/bw0729/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.2.1/boost-1.72.0-qjj5jsztse3c4kmq7q4mr7zire36f2ri' '--with-fgfs=/g/data/jh2/bw0729/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.2.1/fast-global-file-status-1.1-5wpvrhjvdleq44evsge2ulznjudcwuh6' '--disable-examples'

2 errors found in build log:
     319    config.status: creating doc/Makefile
     320    config.status: creating doc/userguide/Makefile
     321    config.status: creating doc/quickstart/Makefile
     322    config.status: creating etc/Makefile
     323    config.status: creating man/Makefile
     324    config.status: creating scripts/STAT
  >> 325    mv: cannot move './confJ5cumG/out' to 'scripts/STAT': No such file or directory
  >> 326    config.status: error: could not create scripts/STAT
``
[spack-build-out.txt](https://github.com/LLNL/STAT/files/4162579/spack-build-out.txt)

**Comment by lee218llnl** [comment]
sorry for the delayed response, I think this is where things start to go wrong from your spack-build.out:

`src/dysect/DysectAPI/Makefile.am:16: warning: source file 'Aggregates/AggregateBE.C' is in a subdirectory,
src/dysect/DysectAPI/Makefile.am:16: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.`

I can't reproduce this error, but there are a bunch of hits on Google if you want to try and debug yourself. I will poke at some of the topics and see if anything looks relevant.

**Comment by lee218llnl** [comment]
Actually, I'm not sure if that warning message is relevant to the error you get:

> config.status: creating scripts/STAT
> mv: cannot move './confJ5cumG/out' to 'scripts/STAT': No such file or directory
> config.status: error: could not create scripts/STAT

I'm wondering if the "scripts" directory does not exist for some reason?

**Comment by BenWibking** [comment]
I think I may be running into filesystem or quota issues on the machine I'm using but for some reason I can't reproduce them when running e.g. `git clone` or even just `touch` or `cp` manually. I also can't reproduce my earlier error. Now `spack` just hangs at the "staging archive" phase:

```
[bw0729@gadi-login-03 bin]$ ./spack install --keep-stage stat@develop^dyninst@10.1.0^gettext
==> Warning: gcc@8.2.1 cannot build optimized binaries for "cascadelake". Using best target possible: "skylake_avx512"
==> Warning: Missing a source id for mrnet@5.0.1-3
==> Warning: Missing a source id for stat@develop
==> 38590: Installing libsigsegv
==> Using cached archive: /g/data/jh2/bw0729/spack/var/spack/cache/_source-cache/archive/3a/3ae1af359eebaa4ffc5896a1aee3568c052c99879316a1ab57f8fe1789c390b6.tar.gz
==> Staging archive: /scratch/jh2/bw0729/tmp/spack-stage/spack-stage-libsigsegv-2.12-uf2drdq7ufxylujfrldq64mq36wfleu3/libsigsegv-2.12.tar.gz
```

Are there any debug flags or vars I can set to see exactly what operation is hanging?

**Comment by lee218llnl** [comment]
It looks like it is trying to use an already downloaded file ("cached archive") in /g/data/jh2/bw0729/spack/var/spack/cache/_source-cache/archive/3a/3ae1af359eebaa4ffc5896a1aee3568c052c99879316a1ab57f8fe1789c390b6.tar.gz. Perhaps you can try removing that and try again? If that doesn't work, you may want to check on the size/timestamps of files in the spack-stage directory that is being printed out in the "Staging archive" message.

**Comment by lee218llnl** [comment]
@BenWibking any updates on you attempt to build STAT via spack?

**Comment by BenWibking** [comment]
The installation now fails with:

```
==> 31888: Installing py-markupsafe
==> Fetching https://pypi.io/packages/source/M/MarkupSafe/MarkupSafe-1.1.1.tar.gz
######################################################################################## 100.0%#=#=-#                                                                                        
curl: (22) The requested URL returned error: 503 
==> Failed to fetch file from URL: https://pypi.io/packages/source/M/MarkupSafe/MarkupSafe-1.1.1.tar.gz
    URL https://pypi.io/packages/source/M/MarkupSafe/MarkupSafe-1.1.1.tar.gz was not found!
==> Fetching from https://pypi.io/packages/source/M/MarkupSafe/MarkupSafe-1.1.1.tar.gz failed.
==> Error: FetchError: All fetchers failed for spack-stage-py-markupsafe-1.1.1-napv4peull4daidepvirrnfdi6qlszcz

/g/data/jh2/bw0729/spack/lib/spack/spack/package.py:1130, in do_fetch:
       1127                raise FetchError("Will not fetch %s" %
       1128                                 self.spec.format('{name}{@version}'), ck_msg)
       1129
  >>   1130        self.stage.create()
       1131        self.stage.fetch(mirror_only)
       1132        self._fetch_time = time.time() - start_time
       1133


==> Error: Failed to install py-markupsafe due to ChildError: FetchError: All fetchers failed for spack-stage-py-markupsafe-1.1.1-napv4peull4daidepvirrnfdi6qlszcz
/g/data/jh2/bw0729/spack/lib/spack/spack/package.py:1130, in do_fetch:
       1127                raise FetchError("Will not fetch %s" %
       1128                                 self.spec.format('{name}{@version}'), ck_msg)
       1129
  >>   1130        self.stage.create()
       1131        self.stage.fetch(mirror_only)
       1132        self._fetch_time = time.time() - start_time
       1133

Traceback (most recent call last):
  File "/g/data/jh2/bw0729/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/g/data/jh2/bw0729/spack/lib/spack/spack/installer.py", line 1046, in build_process
    pkg.do_patch()
  File "/g/data/jh2/bw0729/spack/lib/spack/spack/package.py", line 1170, in do_patch
    self.do_stage()
  File "/g/data/jh2/bw0729/spack/lib/spack/spack/package.py", line 1155, in do_stage
    self.do_fetch(mirror_only)
  File "/g/data/jh2/bw0729/spack/lib/spack/spack/package.py", line 1131, in do_fetch
    self.stage.fetch(mirror_only)
  File "/g/data/jh2/bw0729/spack/lib/spack/spack/util/pattern.py", line 68, in getter
    getattr(item, self.name)(*args, **kwargs)
  File "/g/data/jh2/bw0729/spack/lib/spack/spack/stage.py", line 476, in fetch
    raise fs.FetchError(err_msg, None)
spack.fetch_strategy.FetchError: All fetchers failed for spack-stage-py-markupsafe-1.1.1-napv4peull4daidepvirrnfdi6qlszcz

==> Warning: Skipping build of py-mako since py-markupsafe failed
==> Warning: Skipping build of mesa since py-mako failed
==> Warning: Skipping build of libepoxy since mesa failed
==> Warning: Skipping build of gtkplus since libepoxy failed
==> Warning: Skipping build of py-xdot since gtkplus failed
==> Warning: Skipping build of stat since py-xdot failed
==> Warning: Skipping build of py-pygobject since gtkplus failed
```

**Comment by lee218llnl** [comment]
That URL appears valid to me and I was prompted to download when I enter it in a browser. Sometimes with those fetch errors, you may need to just try again.

**Comment by BenWibking** [comment]
Ok, that works now. I'm back to an earlier error about scripts/STAT. I've checked and the scripts directory does exist, so I'm not sure why it's failing.

```
config.status: creating scripts/STAT
mv: cannot move './confhxK2X8/out' to 'scripts/STAT': No such file or directory
config.status: error: could not create scripts/STAT
```

**Comment by lee218llnl** [comment]
Can you attach your config.log file? Perhaps the ./confhxK2X8/out file is what is missing for some reason.

**Comment by BenWibking** [comment]
Here is my config.log file.
[config.log](https://github.com/LLNL/STAT/files/4400766/config.log)

**Comment by lee218llnl** [comment]
I saw a post in another project that reports one user encountered this error when they had a non-standard `rm` command. Do you alias or wrap `rm`? In my config.status I see this:
`  case $ac_file in
  -) cat "$ac_tmp/out" && rm -f "$ac_tmp/out";;
  *) rm -f "$ac_file" && mv "$ac_tmp/out" "$ac_file";;
  esac \
  || as_fn_error $? "could not create $ac_file" "$LINENO" 5
 ;;`

So it would be possible to get your error message if the `rm` fails. My config.status lines don't appear to be the same as yours, could you perhaps send your config.status too?

**Comment by BenWibking** [comment]
No `rm` is not aliased or wrapped in my environment.
I've attached config.status (renamed so it will accept the upload).
[config.status.txt](https://github.com/LLNL/STAT/files/4406894/config.status.txt)

**Comment by lee218llnl** [comment]
comparing the line numbers, this is where it is failing:

```
  case $ac_file in
  -) cat "$ac_tmp/out" && rm -f "$ac_tmp/out";;
  *) rm -f "$ac_file" && mv "$ac_tmp/out" "$ac_file";;
  esac \
  || as_fn_error $? "could not create $ac_file" "$LINENO" 5
 ;;
```
That means either the "rm -f" is failing or the "mv" is failing. My guess is that the "rm -f" should work OK, as it worked for previous input files. Also, you indicate the scripts directory exists, so it should be able to move files in there. That said, my best speculation is that for some reason $ac_tmp/out does not exist. My next suggestion would be to run the configure under strace (i.e., `strace -f`). You can hack the spack package to do this in var/spack/repos/builtin/spack/package.py by adding this function to the package class:
```
    def configure(self, spec, prefix):
        args = [
            "--with-launchmon=%s"   % spec['launchmon'].prefix,
            "--with-mrnet=%s"       % spec['mrnet'].prefix,
            "--with-graphlib=%s"    % spec['graphlib'].prefix,
            "--with-stackwalker=%s" % spec['dyninst'].prefix,
            "--with-python=%s"      % spec['python'].command.path,
            "--with-boost=%s"       % spec['boost'].prefix,
        ]
        strace = Executable('strace')
        strace('-f', './configure', *self.configure_args())
```
Hopefully that will still fail in configure and provide more debug info. If so, can you send me the spack-build-out.txt file which should contain the strace output? Here's a snippet of what I see when I do this:
```
[pid 61525] execve("/usr/bin/rm", ["rm", "-f", "scripts/STAT"], [/* 146 vars */]) = 0
...
[pid 61526] execve("/usr/bin/mv", ["mv", "./confi2EiJ5/out", "scripts/STAT"], [/* 146 vars */]) = 0
```
In my case they both return a success code of "0".

**Comment by BenWibking** [comment]
The directory `var/spack/repos/builtin/spack` doesn't exist in my spack repo. I tried to modify `lib/spack/spack/package.py` but the output in spack-build-out.txt didn't show anything from strace.

**Comment by BenWibking** [comment]
I am on the `develop` branch, commit `a4b3edd68`. Should I be on a different branch?

**Comment by lee218llnl** [comment]
Sorry I meant var/spack/repos/builtin/packages/stat/package.py. Develop branch is correct
Sent from my iPhone

On Mar 31, 2020, at 11:26 PM, Ben Wibking <notifications@github.com> wrote:

﻿

I am on the develop branch, commit a4b3edd68. Should I be on a different branch?

**Comment by lee218llnl** [comment]
Sorry for the typo. To make sure I didn't make any other mistakes (and to clean up the code a bit), here's a git diff:

```
[lee218@rzwiz2:spack]$ git diff var/spack/repos/builtin/packages/stat/package.py
diff --git a/var/spack/repos/builtin/packages/stat/package.py b/var/spack/repos/builtin/packages/stat/package.py
index 2db8a33..c1e2e42 100644
--- a/var/spack/repos/builtin/packages/stat/package.py
+++ b/var/spack/repos/builtin/packages/stat/package.py
@@ -55,6 +55,10 @@ class Stat(AutotoolsPackage):
 
     patch('configure_mpicxx.patch', when='@2.1.0')
 
+    def configure(self, spec, prefix):
+        strace = Executable('strace')
+        strace('-f', './configure', '--prefix=%s'%prefix, *self.configure_args())
+
     def configure_args(self):
         spec = self.spec
         args = [


```

**Comment by BenWibking** [comment]
I now get an (unrelated?) error when trying to build llvm. I've attached spack-build-out.txt again.
[spack-build-out.txt](https://github.com/LLNL/STAT/files/4448170/spack-build-out.txt)

**Comment by BenWibking** [comment]
Ok, it works if I force it to use llvm@9.0.1. I've attached the (very large) build log for the `scripts/STAT` error with the `strace` patch.
[spack-stat-build-failure.tar.gz](https://github.com/LLNL/STAT/files/4473667/spack-stat-build-failure.tar.gz)

**Comment by lee218llnl** [comment]
I am honestly at a loss here. The relevant strace error output is:

[pid 11044] ioctl(0, TCGETS, 0x7ffd43eb0d30) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 11044] renameat2(AT_FDCWD, "./confCm8JsN/out", AT_FDCWD, "scripts/STAT", RENAME_NOREPLACE) = -1 EINVAL (Invalid argument)
[pid 11044] newfstatat(AT_FDCWD, "scripts/STAT", 0x7ffd43eb0cf0, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
[pid 11044] renameat(AT_FDCWD, "./confCm8JsN/out", AT_FDCWD, "scripts/STAT") = -1 ENOENT (No such file or directory)

It's that last one, the "renameat" that gets a -1 return code that is the problem. For the other generated files, such as etc/Makefile, I see the renameat2 return -1, but then the subsequen renameat returns 0. I honestly don't know how to debug this or fix it. You may want to try building STAT from source outside of spack. You can then point it to the spack-built dyinst, launchmon, graphlib, etc. dependencies.

**Comment by BenWibking** [comment]
Can you explain what the build script is trying to do? It looks like it's trying to rename the `out` file to `scripts/STAT`, detecting a failure, then trying again with a different system call -- is that the case?

Could this be a filesystem issue? There have been a few issues on this cluster recently. If so, I'll raise it with the cluster sysadmins.

I'll also try building from source as you describe.

**Comment by BenWibking** [comment]
For an NFS-mounted filesystem, is this something that could arise due to synchronization/caching issues?

**Comment by lee218llnl** [comment]
First let me say that I am by no means an expert of autoconf/automake, but I have gathered some understanding from generating the build system and from the strace output. Configure is taking input files like etc/Makefile.in, scripts/STAT.in and then generating etc/Makefile, scripts/STAT based on the args passed to configure and what configure finds. Essentially it replaces some variables with some concrete values based on your system, such as what compiler/python/other dependence to use when building the code and generating run scripts. I'm not sure how this can be a filesystem issue as it successfully translates etc/Makefile.in into etc/Makefile, but then fails to do the same for scripts/STAT.in. In both cases, it creates a temporary file with the same path, but for some reason the former succeeds when renaming, while the latter fails. The system call failures are just demonstrating what the underlying sys calls are when "mv" is run. Again, it is using the same sys calls in both cases, but failing in the second case and I really don't know why. 

Please try my suggestion of trying to build directly from source. You can clone the stat repo from github and I believe the build instructions there should work.

You can also `cd` to the spack stage directory and build from there. If you find the config.log, you can see the arguments passed to configure. You can also run configure under `spack build-env <your_stat_spec> configure ...`, and replace <your_stat_spec> with whatever you supply to `spack install` and replace the "..." with the configure args you see in the config.log from the spack stage directory. I hope this all makes sense what I'm hoping to have you run.

I realize there is a major latency in our correspondences, so I'm hoping you can try to debug some of these issues yourself. It's hard for me to diagnose/debug this without being able to reproduce the problem. Sorry for all this trouble. This is a learning experience for me too!

**Comment by BenWibking** [comment]
I tried building from the git repository using `spack build-env` and it compiled and runs successfully. Thank you for your help!

**Comment by lee218llnl** [comment]
Great, glad to hear it installed and ran OK. I hope you find it useful. I will close out this issue.
