### ISSUE TITLE
PYTHONPATH is not properly expanded in stat-gui?

### ISSUE THREAD

**Issue by pramodk** [LLNL/STAT#25]
In the stat-gui script we have following: https://github.com/LLNL/STAT/blob/445537fb93257e9f31ce70acb0bf5d6e6b4b7d50/scripts/STATGUI.in#L78

When I install STAT via Spack, I see following in our installation:

```
export PATH=$PATH:/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/graphviz-2.44.1-ggro3g/bin
export PYTHONPATH=${prefix}/lib/python3.8/site-packages:${exec_prefix}/lib/python3.8/site-packages:

exec /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/python-3.8.3-suxrst/bin/python3.8 ${prefix}/lib/python3.8/site-packages/STATmain.py gui $@
```

Note that PYTHONPATH doesn't contain dependencies like py-xdot. And even if I set `PYTHONPATH` externally, it doesn't capture that because we don't append `:$PYTHONPATH`. So all user provided `PYTHONPATH` is ignored.

As mentioned in https://github.com/LLNL/STAT/issues/15#issuecomment-583139368, Python is often externally installed and we don't have option to use `spack activate`. So I propose following:
* Append `:$PYTHONPATH` in stat-gui when we set PYTHONPATH
* [Optionally] STAT generated module should also have necessary PYTHONPATH for main dependencies.

**Comment by lee218llnl** [comment]
for py-xdot, you need to `spack activate py-xdot`. That will "install" via symlinks it in the appropriate python installation's site-packages directory as if it were directly installed in there. Please let me know if that works.

**Comment by pramodk** [comment]
Thanks @lee218llnl for quick response! 

In https://github.com/LLNL/STAT/issues/15#issuecomment-583139368 I mentioned following: 

>  In our case Python comes from upstreams and not writable to users

When we work with different clusters, python is installed by system engineers and STAT is not provided by default. So we install STAT ourselves and there is no way to run `spack activate` as python is read-only.

To make user experience smoother with manually installed stat, IMO we should at least append `:$PYTHONPATH` in the stat-gui script i.e. just changing:

```
export PYTHONPATH=@pythondir@:@pyexecdir@:@PYTHONPATH@ 
```

to 

```
export PYTHONPATH=@pythondir@:@pyexecdir@:$PYTHONPATH:@PYTHONPATH@ 
```
?

**Comment by lee218llnl** [comment]
@pramodk sounds like a good suggestion. Can you see if #26 looks OK to you?

**Comment by lee218llnl** [comment]
@pramodk, I think I have this fixed so I will close this issue.

**Comment by pramodk** [comment]
thanks @lee218llnl! I just reviewed!
