### ISSUE TITLE
no function info in stat .dot files

### ISSUE THREAD

**Issue by antonl321** [LLNL/STAT#33]
Hello,

I have install STAT develop and 4.1.0 via spack on RHEL 8.3 without gui and without fgfs.

I have tested both versions on a simple mpi code which locks in mpi_recv. In using gcc 8.3.1 and openmpi 4.0.5.2 .
I can attach stat-cl to srun,  the messages generated by stat-cl look fine and I get the stat_results directory. 
When I tried to see a call tree with `dot` or `dotty` I got only a '/'. 
This is understandable because the .dot files generated by stat-cl have no app info, see the following:
```
$ cat stat_results/t3.x.0001/00_t3.x.0001.2D.dot
digraph G {
        graph [type="stat_4_1"];
        node [shape=record,style=filled,labeljust=c,height=0.2];
        0 [pos="0,0", label="/", fillcolor="#AAAAAA", fontcolor="#FFFFFF", function="/", source="(null)", line="(null)", module="(null)", offset="(null)", vars="(null)", pc="(null)"];
```
I have run stat-cl with log enabled as suggested in another post, I attached the logs to this post.
I think that I'm pretty close to have STAT working. Do I miss something obvious?

With thanks,
Lucian Anton

[at1-11.bullx.STAT.log](https://github.com/LLNL/STAT/files/7109610/at1-11.bullx.STAT.log)
[at1-1000.bullx.STATD.log](https://github.com/LLNL/STAT/files/7109611/at1-1000.bullx.STATD.log)

**Comment by lee218llnl** [comment]
@antonl321 Hmm, the logs don't indicate any error. Have you tried attaching gdb to one of the application processes to see if that works? Also, did you compile with -g and make sure not to strip the binary? 

Another simple test you can do is to build the example in https://github.com/LLNL/STAT/blob/develop/examples/src/mpi_ringtopo.c and see if you can get STAT to work on that.

**Comment by antonl321** [comment]
Hi Lee,

Thanks for the suggestions.
I have tested gdb, its backtrace looks fine. I have tested also your test code and I got the same behaviour.
Also I have tried some of stat-cl options (threads, comprehensive) without any change in bevaviour.
One oddity I have noticed is that I cannot login to the slurm allocates nodes after stat is loaded by spack (see below).
But I'm not sure that tis is related to my problem.

```
$ . ~/sch/spack/share/spack/setup-env.sh
$ spack load stat@develop
$ salloc -N 1 -p compute -t 60
salloc: Granted job allocation 287065
salloc: Waiting for resource configuration
salloc: Nodes at1-1005 are ready for job
$ ssh at1-1005
ssh: symbol lookup error: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
```

**Comment by lee218llnl** [comment]
Regarding `spack load` and the error you get, it is probably due to to LD_LIBRARY_PATH being modified. I will suggest that you do not `spack load stat` and rather run the full path to stat-cl directly, or just add the appropriate bin directory to your $PATH.

As for the backtraces, I'm wondering if dyninst is having problems for some reason. Can you run `spack spec stat@develop` to see which version of dyninst it is using? It may also be worth building STAT with a different version of dyninst to see if that helps. Do you have any other debuggers (i.e., Allinea Forge/DDT or TotalView) that you can test too?

**Comment by antonl321** [comment]
I had a look at dyninst. I reinstalled it with the stat pach and I reinstalled stat. No change unfortunately.
I attach the output of `spack spec -I stat@develop` and also the output of strace on stat-cl
[spec.log](https://github.com/LLNL/STAT/files/7145054/spec.log)
[strace.log](https://github.com/LLNL/STAT/files/7145056/strace.log)

**Comment by lee218llnl** [comment]
Unfortunately an strace of stat-cl is not going to provide much information, as the problem is in the STATD process that is being launched alongside the application.

That aside, I am not sure what you mean by reinstalling stat with the patch. My recommendation is to try a different dyninst version. So if you spack install command was previously:

spack install stat ~gui ~fgfs

Please now try

spack install stat ~gui ~fgfs ^dyninst@10.2.1

Note that this will install stat into a different .../spack/opt/... directory, so be sure to test with the newly installed version.

      -Greg

**Comment by antonl321** [comment]
Hello,

I tried your suggestion with careful checks, unfortunately I got the same result.
Anyway while runing `LD_DEBUG=libs stat-cl ...` I found the following errors in the output about undefined symbols. Perhaps this gives you a hint.

 ```
...
   1398294:     calling init: /lus/pfs1/scratch/atosla/spack/opt/spack/linux-rhel8-zen/gcc-8.3.1/stat-4.1.0-hvxfopk6xfiqtu5xhalomat7bveunxwn/lib/STAT_FilterDefinitions.so
   1398294:
   1398294:     /lus/pfs1/scratch/atosla/spack/opt/spack/linux-rhel8-zen/gcc-8.3.1/stat-4.1.0-hvxfopk6xfiqtu5xhalomat7bveunxwn/lib/STAT_FilterDefinitions.so: error: symbol lookup error: undefined symbol: filterInit_get_state (fatal)
   1653925:
   1653925:     calling init: /lus/pfs1/scratch/atosla/spack/opt/spack/linux-rhel8-zen/gcc-8.3.1/stat-4.1.0-hvxfopk6xfiqtu5xhalomat7bveunxwn/lib/STAT_FilterDefinitions.so
   1653925:
   1653925:     /lus/pfs1/scratch/atosla/spack/opt/spack/linux-rhel8-zen/gcc-8.3.1/stat-4.1.0-hvxfopk6xfiqtu5xhalomat7bveunxwn/lib/STAT_FilterDefinitions.so: error: symbol lookup error: undefined symbol: filterInit_get_state (fatal)
   1398294:     /lus/pfs1/scratch/atosla/spack/opt/spack/linux-rhel8-zen/gcc-8.3.1/stat-4.1.0-hvxfopk6xfiqtu5xhalomat7bveunxwn/lib/STAT_FilterDefinitions.so: error: symbol lookup error: undefined symbol: statMerge_get_state (fatal)
   1653925:     /lus/pfs1/scratch/atosla/spack/opt/spack/linux-rhel8-zen/gcc-8.3.1/stat-4.1.0-hvxfopk6xfiqtu5xhalomat7bveunxwn/lib/STAT_FilterDefinitions.so: error: symbol lookup error: undefined symbol: statMerge_get_state (fatal)
Tool daemons launched and connected!
   1398294:     /lus/pfs1/scratch/atosla/spack/opt/spack/linux-rhel8-zen/gcc-8.3.1/stat-4.1.0-hvxfopk6xfiqtu5xhalomat7bveunxwn/lib/STAT_FilterDefinitions.so: error: symbol lookup error: undefined symbol: STAT_checkVersion_get_state (fatal)
   1653925:     /lus/pfs1/scratch/atosla/spack/opt/spack/linux-rhel8-zen/gcc-8.3.1/stat-4.1.0-hvxfopk6xfiqtu5xhalomat7bveunxwn/lib/STAT_FilterDefinitions.so: error: symbol lookup error: undefined symbol: STAT_checkVersion_get_state (fatal)
Attaching to application...
Attached!
Application already paused... ignoring request to pause
Sampling traces...
Traces sampled!
...
```

**Comment by lee218llnl** [comment]
the problem is not in stat-cl, which is the tool front-end that merges the traces from the STATD daemons. The problem is that the STATD daemons are not getting traces, or getting empty traces from the application process. These empty traces are sent to the frontend. The debugging we need to do is to figure out why the STATD daemons are getting empty traces or having trouble getting traces. Let me see if I can figure out out to get the Dyninst library that it uses to produce some logs.

**Comment by lee218llnl** [comment]
can you try adding `-l SW` to your stat-cl command line, in addition to the other -l and -L arguments you already provided? Please attach the STATD log after you do that.

**Comment by antonl321** [comment]
here it comes
[at1-1001.bullx.STATD.log](https://github.com/LLNL/STAT/files/7157386/at1-1001.bullx.STATD.log)

**Comment by lee218llnl** [comment]
Hmm, after these messages

``<Sep 13 21:04:55> <STAT_BackEnd.C:1653> Attaching to all application processes
[process.C:8567-U] - Setting thread mode to HandlerThreading
[process.C:8588-U] - New state uses handler threading, running handler thread```

I expect to see something like this (from a log file in my test run):

```<Sep 13 13:49:15> <STAT_BackEnd.C:1773> Attaching to process a.out, pid 58805, MPI rank 0```

But we don't see that in your case. The STATD daemon does a loop over all processes in the processes in its process table and will print a message like the one above for each process it finds, but it appears to have an empty process table. The process table should be received using LaunchMON, so I'm not sure why it is empty. Perhaps @dongahn may have a suggestion, but I think we need to get a look inside LaunchMON to see why the STATD daemon is getting an empty process table from LaunchMON when calling:

```    lmonRet = LMON_be_getMyProctab(proctab_, &proctabSize_, size);```

**Comment by lee218llnl** [comment]
@antonl321 Can you append this to your spack/var/spack/repos/builtin/packages/launchmon/package.py:

```
    def configure_args(self):
        return ["--enable-verbose=/home/atosla/lmonlogdir"]
```

Then run `spack uninstall --dependents launchmon` and answer "y" when it asks if you want to proceed. Then once again install STAT using the spack install command that you had previously used to install STAT. After that, please run STAT and send the output from the terminal as well as the contents of the directory /home/atosla/lmonlogdir.

**Comment by lee218llnl** [comment]
Actually, if you can, please send all the files from the directory that STAT created when it says "Results written to". That will help see what the frontend has for the process table too. Ultimately, I think (just a hypothesis right now) there may be a mismatch between the hostnames in the front-end's process table and the ones that the daemons get when they call gethostname, thus they don't find their entries.

**Comment by antonl321** [comment]
Hi,

I found out that there is quirk on the system I try to install STAT. Long name for compute nodes (i.e. \<node-name\>.bullx produced by hostname) cannot be used to connect to compute nodes. I think that lmon
 trips on this, see the out file attached. The error file is empty. I'll try to have this fixed and test STAT again. 
Is any way to tell lmon to use short names as produces by hostname -s?
[be.stdout.1200629.at1-1002.bullx.log](https://github.com/LLNL/STAT/files/7163648/be.stdout.1200629.at1-1002.bullx.log)

**Comment by lee218llnl** [comment]
@antonl321 not to be pedantic, but it actually is not a problem connecting. The daemons are connected properly. The problem is that after they are connected, the STAT frontend is trying to tell each STAT backend daemon which MPI application processes it needs to attach to. The frontend has a process table with node names like "at1-1002", but when the backend daemons call gethostname, they get "at1-1002.bullx". Thus when the backend daemon scans the full process table to look for that backend daemon's processes, it doesn't find any since the string comparison fails. I'm not sure what the best solution is. Perhaps we could patch launchmon to have the backend daemon truncate its hostname at the first "." character. @dongahn do you have any ideas?

That aside, is the "." in the hostname something you can ask you system administrators about? Having a "." in the hostname seems like an ill-advised practice, so I'm not sure what the reason for that is.

**Comment by antonl321** [comment]
Thanks for comments. Sys admin on my side is looking into this and try to fix it. As far as I understand it is about a proxy configuration.
I'll get back with news soon, I hope.

**Comment by antonl321** [comment]
Hello,

I found out that the name issue is not an issue on an other system which is very close to the first one (hardware and software).
I attach the stat-cl output dir. I can see the functions names in .dot files, but there are also lots of null values. Is this right? dot generates a plot with boxes and links but no other info.

[t3.x.0000.tar.gz](https://github.com/LLNL/STAT/files/7171063/t3.x.0000.tar.gz)

**Comment by lee218llnl** [comment]
@antonl321 The dot files that STAT generates are designed to be viewed in the stat-view GUI. I can view it with my stat-view and have attached a pdf export of the 3D dot file. Can you see if you can get STAT to build with the GUI enabled in spack now?

[t3.x.3D.pdf](https://github.com/LLNL/STAT/files/7171207/t3.x.3D.pdf)

**Comment by antonl321** [comment]
Ok, thanks. I'm trying now a build STAT with GUI on the new system. It takes a while to build llvm. On the other system the GUI build failed because of graphical lib. I'll get back to you when after the build ends.

**Comment by antonl321** [comment]
When trying to build with the graphical interface I get this failure for the pango library, see below.
Any hints to fix its build? I found strange that in src there is no cofigure or autotools files.

```
==> Installing pango-1.48.0-574add2q3scg2wat5htthrha527olql7
==> No binary for pango-1.48.0-574add2q3scg2wat5htthrha527olql7 found: installing from source
==> Using cached archive: /home/atosla/Tools/spack/var/spack/cache/_source-cache/archive/39/391f26f3341c2d7053e0fb26a956bd42360dadd825efe7088b1e9340a65e74e6.tar.xz
==> No patches needed for pango
==> pango: Executing phase: 'autoreconf'
==> Error: AttributeError: module 'spack.pkg.builtin.pango' has no attribute 'autoreconf'

/home/atosla/Tools/spack/lib/spack/spack/build_systems/autotools.py:277, in autoreconf:
        274            # --install, --verbose, --force
        275            autoreconf_args = ['-ivf']
        276            autoreconf_args += self.autoreconf_search_path_args
  >>    277            autoreconf_args += self.autoreconf_extra_args
        278            m.autoreconf(*autoreconf_args)

See build log for details:
  /home/atosla/Tools/spack/tmp/spack-stage/spack-stage-pango-1.48.0-574add2q3scg2wat5htthrha527olql7/spack-build-out.txt
```

**Comment by lee218llnl** [comment]
@antonl321 for the spack error installing pango, can you search the spack github page to see if anyone else has reported this? If not, I will suggest submitting an issue to the spack project on github.

**Comment by lee218llnl** [comment]
In fact, I found https://github.com/spack/spack/issues/25651, which suggests add "^pango@1.42.0" to your spack install command.

**Comment by antonl321** [comment]
That worked, thanks! However rust is misbehaving when building librsvg

```
 >> 217    error: failed to remove /home/atosla/Tools/spack/tmp/spack-stage/sp
            ack-stage-librsvg-2.51.0-wtbuqngyuvk5k4vfkbtcz2hp2dyzjb26/spack-src
            /target/release/build/libc-84ba192b0b45799a/build_script_build-84ba
            192b0b45799a.build_script_build.7tv583r9-cgu.0.rcgu.o: No such file
             or directory (os error 2)
```

I never used rust, any hint is much appreciated.

**Comment by lee218llnl** [comment]
@antonl321 I am not a rust user either. I suggest you submit an issue to the spack project. Please pass me a link to the issue when you do. Also, I will suggest including more error output when you submit the issue. Sometimes it helps to see the lines before the error to see which command is running and get more context.

**Comment by antonl321** [comment]
Well, librsvg build was successful  with `spack install -j 1 ...` and I got stat-gui working.

One package is left outstanding, fgfs which fails with the following

```
==> No patches needed for fast-global-file-status
==> fast-global-file-status: Executing phase: 'autoreconf'
==> Error: AttributeError: module 'spack.pkg.builtin.fast-global-file-status' has no attribute 'autoreconf'

/home/atosla/Tools/spack/lib/spack/spack/build_systems/autotools.py:277, in autoreconf:
        274            # --install, --verbose, --force
        275            autoreconf_args = ['-ivf']
        276            autoreconf_args += self.autoreconf_search_path_args
  >>    277            autoreconf_args += self.autoreconf_extra_args
        278            m.autoreconf(*autoreconf_args)

See build log for details:
  /home/atosla/Tools/spack/tmp/spack-stage/spack-stage-fast-global-file-status-master-pn3352ag6dyexe2wwmdh3b4s2husjmad/spack-build-out.txt
```
Any hints on that? It seems to me that the bootstrap script is not run.

**Comment by lee218llnl** [comment]
For FGFS, it looks like we need to add:

```
    depends_on('autoconf', type='build')
    depends_on('automake', type='build')
```

to spack/var/spack/repos/builtin/packages/fast-global-file-status/package.py

I will put in a pull request to the spack project, but you can manually add this in the meantime.

**Comment by lee218llnl** [comment]
https://github.com/spack/spack/pull/26005

**Comment by antonl321** [comment]
The fixed worked fine. I could inspect easily with STAT a run with with ~580 nodes (>4000 MPI ranks).
Thank you for the prompt and useful suggestions.
I'm closing this issue.
