### ISSUE TITLE
SDBG_TRACER_ERROR (ERROR) while attaching hanging mpi process

### ISSUE THREAD

**Issue by moguzhankarakaya** [LLNL/STAT#34]
Hi, 

I am having issue while trying to get stack analysis out of a hang process with stat-cl. I am using `spack` to install `STAT@4.0.2`. The example I am trying to run is from STAT repository /examples/src/mpi_ringtopo.c.  I took this example and compiled it with mpicc compiler coming with intel-oneapi hpc toolkit. Then I tried to run it simple by

`mpiexec.hydra -n 4 mpi_ringtopo`

Again, I use mpiexec.hydra coming from intel-oneapi hpc toolkit. However, when I tried to connect to the process by

`stat-cl <PID>`

I get the following message

`Launching application and tool daemons...`
`<ProcTracer> (INFO): attach returned non-zero for 5395, continue...`
`SDBG_TRACER_ERROR (ERROR): [filename: sdbg_linux_ptracer.hxx, linenum: 95] [linux_ptracer_t::tracer_attach] error returned` `from ptrace Operation not permitted`
`SDBG_TRACER_ERROR (ERROR): BACKTRACE:`
`launchmon: linux_ptracer_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t,` `elf_wrapper>::tracer_attach(process_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct,` `my_thrinfo_t, elf_wrapper>&, bool, int)`
`launchmon: linux_launchmon_t::handle_attach_event(process_base_t<unsigned long, unsigned long, unsigned long,` `user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>&)`
`launchmon: driver_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t,` `elf_wrapper>::drive_engine(opts_args_t*)`
`launchmon: linux_driver_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct>::driver_main(int,` `char**)`
`launchmon: main`
`libc.so.6: __libc_start_main`
`launchmon: _start`

I also tried mpi compiler and mpiexec with mpich distro. The result was exactly the same. I also tried to create the process with the following commands

`stat-cl -C mpiexec.hydra -n 4 mpi_ringtopo`

or 

`stat-cl -C mpiexec.hydra -n 4 mpi_ringtopo 60`

The latter has argument to mpi_rigntopo to hang the process X seconds and continue afterwards. In this case I get the following error

`Launching application and tool daemons...`
`<LMON FE API> (ERROR): read_lmonp_msg returned a negative return code`
`<LMON FE API> (ERROR): front end's connection to launchmon engine is disconnected?`

I have seen the previous issue similar to this. But it is closed, as it was caused by finishing job before STAT could connect. However, in my case, the mpi process is started and hanged in the infinite loop. Shouldn't LaunchMON connect to it?

Thanks in advance for help

**Comment by lee218llnl** [comment]
The error message, "error returned from ptrace Operation not permitted" indicates that your OS may have debugging restrictions that are not allowing launchmon to attach to it. Are you able to attach gdb or any other debugger to mpiexec.hydra as a test? @dongahn may have more advice too.
