### ISSUE TITLE
STAT_merge.dot strangely formatted

### ISSUE THREAD

**Issue by roblatham00** [LLNL/STAT#39]
The stat user guide says I should get a tree view like this, with nodes labeled by function name and edges labeled by node counts and rank identifiers. 

What I'm supposed to get:
![image](https://user-images.githubusercontent.com/2278417/154696299-774e4b4a-e6b8-44a9-88b6-2587c6d3ae5f.png)

I'm not using stat-view, but instead rendering the dot files myself with ` dot -Tpng STAT_merge.dot`

What I actually see:
![image](https://user-images.githubusercontent.com/2278417/154696586-2d63387a-ccb7-4bfb-841c-f9a833e4964c.png)

Looking at the .dot, the `label=` field is indeed `""` or `"(null)"`.  Here's a typical node

```
 1608259434 [pos="0,0", label="", fillcolor="#c71c71", fontcolor="#000000", function="HG_Core_trigger", source="/tmp/robl/spack-stage/spack-stage-mercury-master-zobm223atxe3oegpz3hymvv3ilyhb4ci/spack-src/src/mercury_core.c", line="5071", module="(null)", offset="(null)", vars="(null)", pc="(null)"];
```

and here's a typical edge:
```
 1653371223 -> 1654617382 [label="(null)", bv="[0-1,3-4,8-9]", count="(null)", rep="(null)", sum="(null)", tbv="(null)", tcount="6", tbvsum="227"]
```

**Comment by roblatham00** [comment]
thanks for clarifying.  I see now spack builds STAT with it's `gui` variant disabled by default.  I tried building STAT with the +gui variant but it brought in dependencies that don't readily compile on ORNL's summit.  

Do you want a separate issue to track "spack on summit" ?   As I mentioned in #35 I have to use python2 on summit, but the py-gtk dependencies appear to want python3

I do sometimes have trouble exporting my X display from these remote machines.  Is there a 'stat-cl' way to export to png/pdf?

**Comment by lee218llnl** [comment]
Unfortunately there isn't currently a way to export with stat-cl. I'm going to run some tests with a spack build on our ppc64le CORAL systems to see if I can get everything working and hopefully that will translate to summit. In the meantime, you could try installing stat with +gui on some other system. Building on x86 is generally easier. You could then generate the .dot files on summit and copy them and then open on the other system. If there is an immediate need, I can also "translate" STAT .dot files for you if there aren't any concerns about sending me the contents. You can email me at lee218@llnl.gov if you like.

Feel free to open a spack on summit issue.
