### ISSUE TITLE
can't open file '/lib/python3.9/site-packages/STATmain.py'

### ISSUE THREAD

**Issue by antonl321** [LLNL/STAT#42]
Hi,

I have installed with spack the latest STAT and the launch fails with the message from below:

/lus/h2resw01/hpcperm/la/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/python-3.9.12-5ac5g7upuz2pwa7x6oxpxvx7leq32a2q/bin/python3.9: can't open file '/lib/python3.9/site-packages/STATmain.py': [Errno 2] No such file or directory

An install that I have done on a similar system in February worked fine. the only difference I spotted is that the new install uses a slightly newer version of python: 3.9.12 vs 3.9.9

Any idea of what's going on here? Python should be looking in the spack dirs for the STATmain.py.

Lucian Anton

**Comment by antonl321** [comment]
Ok, following our lead I found that PYTHON_PREFIX was not defined. Spack should have fix it, anyway.
I set it to correct value but I get this symbol error at launch. Any hint ?

  2711156:     /lus/h2resw01/hpcperm/la/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gdk-pixbuf-2.42.6-lm3clg77j3q3dpmhogldhwgpctus7fv5/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: error: symbol lookup error: undefined symbol: g_module_check_init (fatal)
   2711156:     /lus/h2resw01/hpcperm/la/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gdk-pixbuf-2.42.6-lm3clg77j3q3dpmhogldhwgpctus7fv5/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: error: symbol lookup error: undefined symbol: g_module_unload (fatal)

Cheers,

Lucian

**Comment by lee218llnl** [comment]
Can you try running:

> ldd /lus/h2resw01/hpcperm/la/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gdk-pixbuf-2.42.6-lm3clg77j3q3dpmhogldhwgpctus7fv5/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so

That symbol should be defined in the libgtk library:

> $ nm gtkplus-3.24.29-avzxhxmi47tnyxenhob6shys4nbfk5eb/lib/libgtk-3.so.0.2404.25 | grep g_module_unload
> 00000000003d9a50 t gtk_theming_module_unload

**Comment by antonl321** [comment]
ldd output looks fine but some of the symbols are not found by nm.

I should mention perhaps that when I launch stat-gui the STAT the start window appears for a fraction of a second and then it crashes.

LD_DEBUG=libs,symbols dump this error for the first unfound symbol.  Wrong version of libglib or similar?

   1581989:     symbol=g_module_check_init;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/glib-2.72.1-nzjzdpez3drwyclhuflt52565bs4ll5e/lib/libglib-2.0.so.0 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/pcre-8.45-cs5a2o5hjykrd32yhhzroryw3tv4tdsi/lib/libpcre.so.1 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gettext-0.21-yfy7h2cxk2oktg5zpps67pgh26k2f3af/lib/libintl.so.8 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/libiconv-1.16-dn3n7yl2rfhh7noojqwtn2e5lv5fpwha/lib/libiconv.so.2 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lib64/libpthread.so.0 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lib64/libc.so.6 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
   1581989:     /lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/glib-2.72.1-nzjzdpez3drwyclhuflt52565bs4ll5e/lib/libglib-2.0.so.0: error: symbol lookup error: undefined symbol: g_module_check_init (fatal)
   1581989:     symbol=g_module_unload;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/glib-2.72.1-nzjzdpez3drwyclhuflt52565bs4ll5e/lib/libglib-2.0.so.0 [0]
   1581989:     symbol=g_module_unload;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/pcre-8.45-cs5a2o5hjykrd32yhhzroryw3tv4tdsi/lib/libpcre.so.1 [0]
   1581989:     symbol=g_module_unload;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gettext-0.21-yfy7h2cxk2oktg5zpps67pgh26k2f3af/lib/libintl.so.8 [0]
   1581989:     symbol=g_module_unload;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/libiconv-1.16-dn3n7yl2rfhh7noojqwtn2e5lv5fpwha/lib/libiconv.so.2 [0]
   1581989:     symbol=g_module_unload;  lookup in file=/lib64/libpthread.so.0 [0]
   1581989:     symbol=g_module_unload;  lookup in file=/lib64/libc.so.6 [0]
   1581989:     symbol=g_module_unload;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
   1581989:     /lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/glib-2.72.1-nzjzdpez3drwyclhuflt52565bs4ll5e/lib/libglib-2.0.so.0: error: symbol lookup error: undefined symbol: g_module_unload (fatal)
   1581989:     symbol=g_module_check_init;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/glib-2.72.1-nzjzdpez3drwyclhuflt52565bs4ll5e/lib/libgobject-2.0.so.0 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/glib-2.72.1-nzjzdpez3drwyclhuflt52565bs4ll5e/lib/libglib-2.0.so.0 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/libffi-3.4.2-24yl6c4iaqcrcs5gc2odpxcx2s6yivu2/lib64/libffi.so.8 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lib64/libc.so.6 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/pcre-8.45-cs5a2o5hjykrd32yhhzroryw3tv4tdsi/lib/libpcre.so.1 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/gettext-0.21-yfy7h2cxk2oktg5zpps67pgh26k2f3af/lib/libintl.so.8 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/libiconv-1.16-dn3n7yl2rfhh7noojqwtn2e5lv5fpwha/lib/libiconv.so.2 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lib64/libpthread.so.0 [0]
   1581989:     symbol=g_module_check_init;  lookup in file=/lib64/ld-linux-x86-64.so.2 [0]
   1581989:     /lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/glib-2.72.1-nzjzdpez3drwyclhuflt52565bs4ll5e/lib/libgobject-2.0.so.0: error: symbol lookup error: undefined symbol: g_module_check_init (fatal)

**Comment by antonl321** [comment]
I got a core file from the crash. Do you know which executable I have to pass to gdb together with the core file?

**Comment by lee218llnl** [comment]
You can pass it the python executable.

**Comment by antonl321** [comment]
with export PYTHONDEVMODE=1 I get the following

  label = gtk.Label("Please Wait...")
/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/stat-develop-rv3h57xami2zet7347sasplfvntpesq3/lib/python3.9/site-packages/STATGUI.py:839: DeprecationWarning: Gtk.ScrolledWindow.add_with_viewport is deprecated
  self.sw.add_with_viewport(vbox)
Fatal Python error: Segmentation fault

Current thread 0x000015330427f740 (most recent call first):
  File "/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/python-3.9.12-5ac5g7upuz2pwa7x6oxpxvx7leq32a2q/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 580 in run
  File "/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/stat-develop-rv3h57xami2zet7347sasplfvntpesq3/lib/python3.9/site-packages/STATGUI.py", line 1260 in on_attach
  File "/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/stat-develop-rv3h57xami2zet7347sasplfvntpesq3/lib/python3.9/site-packages/STATGUI.py", line 424 in __init__
  File "/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/stat-develop-rv3h57xami2zet7347sasplfvntpesq3/lib/python3.9/site-packages/STATGUI.py", line 2481 in STATGUI_main
  File "/lus/h2resw01/hpcperm/atosla/Tools/spack/opt/spack/linux-rhel8-zen/gcc-8.4.1/stat-develop-rv3h57xami2zet7347sasplfvntpesq3/lib/python3.9/site-packages/STATmain.py", line 138 in <module>
Segmentation fault (core dumped)

the source code in Gtk.py:580 is
`    578         with register_sigint_fallback(self.destroy):
    579             with wakeup_on_signal():
    580                 return Gtk.Dialog.run(self, *args, **kwargs)
    581 
`

**Comment by lee218llnl** [comment]
It might help if you run gdb on the core file or run STAT under gdb so we can see where in the GTK implementation it is seg faulting. Based on the python trace, though, this looks like it is not a STAT bug, but rather a GTK bug.

**Comment by antonl321** [comment]
I don't understand this. I build with python 3.9.9 which works on another system (same SW stack) and I get the the crash. Not many other version diffs in the spack dependencies between the two installations.
 
The first problem with the new install is that PYTHON_PREFIX is not defined, hence the first failure. Do you know if this variable is comes form spack environment or it belongs to STAT package?

**Comment by lee218llnl** [comment]
I was able to track the change to moving from automake 1.15 to automake 1.16. With that in mind, can you `spack uninstall -a stat' to remove your current stat installations and then reinstall stat with spack adding ^automake@1.15. Let me know if that fixes it for you. If so, I will update the spack package to reflect this until I can fix the issue in the STAT build system itself.

**Comment by lee218llnl** [comment]
the spack PR was merged. If you do a git pull in your spack directory, you should get an updated stat package.py that forces automake version 1.15 (and also dyinst 11.X). Please let me know if this works for you.

**Comment by lee218llnl** [comment]
OK, I'm glad the PYTHON_PREFIX issue is fixed. I too see seg faults with stat-gui. It's not clear if the crash in the link you sent is related. FWIW, here is part of the trace for the STAT GUI crash:


```g_callable_info_free_closure,               FP=7fffffffa170
_pygi_invoke_closure_free,                  FP=7fffffffa190
     g_source_callback_unref,                    FP=7fffffffa1a0
     g_source_destroy_internal,                  FP=7fffffffa1d0
     g_main_context_dispatch,                    FP=7fffffffa240
     g_main_context_iterate.constprop.0,         FP=7fffffffa2a0
     g_main_loop_run,                            FP=7fffffffa2c0
gtk_dialog_run,                             FP=7fffffffa330
     ffi_call_unix64,                            FP=7fffffffa350
     ffi_call_int,                               FP=7fffffffa400
pygi_invoke_c_callable,                     FP=7fffffffa4b0
pygi_function_cache_invoke,                 FP=7fffffffa520
_PyObject_Call,                             FP=7fffffffa560
do_call_core,                               FP=7fffffffa690```

I am going to try building a few more ways to see if we can work around this.

**Comment by lee218llnl** [comment]
Based on a diff of your outputs and a google search of the stack trace, I found https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/283 and figured out that this issue is with the move from libffi@3.3 to libffi@3.4.2. If you add `^libffi@3.3`, then you will not get the seg fault. I will work on a PR for spack and py-xdot.

**Comment by antonl321** [comment]
Tested on my system. Works fine. 
Thanks for your prompt help!
