### ISSUE TITLE
Segmentation fault (core dumped) when STATGUI starts

### ISSUE THREAD

**Issue by ylniu** [LLNL/STAT#6]
Dear authors,

Thanks very much for providing such good debugging software. I try to install STAT on **CentOS 64 bit operation system(gcc-4.8.5, gfortran-4.8.5, mpich2-1.5, python-2.7.5)**. The dependences are a bit complex. Some libraries are installed in lib directory and some else in lib64. The manual does not mention to install other libraries. For example:

yum install elfutils-libelf-devel
yum install python-devel
yum install openssl-devel
yum install pygtk2-devel
binutils
yum install boost-devel

I tried to finish the install process, and was glad to see the executable files in STAT/bin. But when I started STATGUI, there appeared Segmentation fault (core dumped) message.
I found the problem was located at STAT/lib/python/site-packages/STAT.py, line 22.:

  9 from sys import version_info
 10 if version_info >= (2,6,0):
 11     def swig_import_helper():
 12         from os.path import dirname
 13         import imp
 14         fp = None
 15         try:
 16             fp, pathname, description = imp.find_module('_STAT', [dirname(__file__)])
 17         except ImportError:
 18             import _STAT
 19             return _STAT
 20         if fp is not None:
 21             try:
 **22                 _mod = imp.load_module('_STAT', fp, pathname, description)**
 23             finally:
 24                 fp.close()
 25             return _mod
 26     _STAT = swig_import_helper()
 27     del swig_import_helper
 28 else:
 29     import _STAT
 30 del version_info

The file _STAT.so may be compiled from src/STAT_wrap.C, which is generated by SWIG automaticly, And I am not very familiar with C++ and python programs, do not know how to debug this problem. I just want to use STAT to debug gfortran+MPI parallel programs. So my questions are:
1. How to debug and solve this problem ?
2. Are there any groups (e.g. google group) to discuss installation and experience to use STAT, or we can just discuss all the issues in github?

I am very glad to introduce this excellent software to my colleagues who need paralell debugging, while the installation has baffled me. Can I have any hints to solve this problem?

Thanks in advance for any reply!

**Comment by lee218llnl** [comment]
@ylniu Can you get a backtrace of the seg fault with GDB? There are two ways to do this, first is to get a full core file generated on the seg fault and then run `gdb <path_to_python> <your_core_file_name>. The second is to modify the stat-gui shell script to `exec gdb python ...` In either case, once you have gdb up, you can enter "bt" to get the stack trace. If you can copy and past the backtrace information, I may be able to help you debug this.

**Comment by lee218llnl** [comment]
@ylniu Since this is two years old and I haven't heard back from you, I will close this issue. Feel free to reopen it if you want to revisit the issue.
