### ISSUE TITLE
"Configuring incomplete,errors occurred" occured when I installed StackWalker

### ISSUE THREAD

**Issue by buaaluwentao** [LLNL/STAT#7]
I was trying to install STAT on my ubuntu-x86_64, but when I ran ./script-stat-install I encountered many errors,so I write a script named test whose content as follows to install Dyninst sololy:
#__________________________________________________________________________
#!/bin/bash
set -ex
#echo "Step 3 of 6: Downloading StackWalker"
#wget -q http://www.dyninst.org/sites/default/files/downloads/dyninst/8.2.1/DyninstAPI-8.2.1.tgz
export INSTALLDIR=/home/luwentao/software/STAT
export STAT_BUILD_LOG=$PWD/log.txt
tar xzf DyninstAPI-8.2.1.tgz
mv Dyninst-8.2.1 3-Dyninst
cd 3-Dyninst
mkdir build
cd build
echo "Configuring..."
echo "Cmake configure"
cmake -D CMAKE_INSTALL_PREFIX=$INSTALLDIR -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++ -D LIBDWARF_INCLUDE_DIR=$INSTALLDIR/include -D LIBDWARF_LIBRARIES=$INSTALLDIR/lib/libdwarf.so -D LIBELF_INCLUDE_DIR=/usr/include -D LIBELF_LIBRARIES=/usr/lib/x86_64-linux-gnu/libelf.so .. >> $STAT_BUILD_LOG 2>&1
#--with-default-component=StackwalkerAPI --disable-testsuite >> $STAT_BUILD_LOG 2>&1
echo "Compiling... "
make >> $STAT_BUILD_LOG 2>&1
#make test-full
echo "Installing..."
make install >> $STAT_BUILD_LOG 2>&1
cd ../..
echo "Done."
echo
#_____________________________________________________________________________

the directory of STAT as follows:
/home/luwentao/software/STAT
luwentao@luwentao:~/software/STAT$ ls
1-libdwarf               3-Dyninst-b4  bootstrap     DyninstAPI-8.2.1.tgz  INSTALL        Makefile.am          share
2-launchmon-1.0-release  4-mrnet       ChangeLog     dyninst_patches       lib            man                  src
3-Dyninst                5-graphlib    config        error.txt             libdwarf-code  mrnet_4.1.0.tar.gz   STATlogo.gif
3-Dyninst-b              6-STAT        configure.ac  etc                   LICENSE        README.md            test
3-Dyninst-b2             AUTHORS       doc           examples              log-b.txt      scripts              useless.txt
3-Dyninst-b3             bin           Doxyfile      include               log.txt        script-stat-install
and I can confirm that gcc, g++,libdwarf(installed under directory STAT),libelf were installed rightly,their description as follows:
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
luwentao@luwentao:~/software/STAT$ dpkg --list | grep "libelf"
ii  libelf-dev:amd64                                      0.158-0ubuntu5.2                                    amd64        libelf1 development libraries and header files
ii  libelf1:amd64                                         0.158-0ubuntu5.2                                    amd64        library to read and write ELF files
ii  libelfg0:amd64                                        0.8.13-5                                            amd64        an ELF object file ac
the part of content  of CMakeOutput.log as follows:
______________________________________________________________________________
  implicit dirs: [/usr/lib/gcc/x86_64-linux-gnu/4.8;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib]
  implicit fwks: []

Performing C++ SOURCE FILE Test _HAS_CXX11_FLAG succeded with the following output:
Change Dir: /home/luwentao/software/STAT/3-Dyninst/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/make "cmTryCompileExec661944226/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec661944226.dir/build.make CMakeFiles/cmTryCompileExec661944226.dir/build
make[1]: Entering directory `/home/luwentao/software/STAT/3-Dyninst/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/luwentao/software/STAT/3-Dyninst/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building CXX object CMakeFiles/cmTryCompileExec661944226.dir/src.cxx.o
/usr/bin/g++    -D_HAS_CXX11_FLAG   -std=c++11 -o CMakeFiles/cmTryCompileExec661944226.dir/src.cxx.o -c /home/luwentao/software/STAT/3-Dyninst/build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTryCompileExec661944226
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec661944226.dir/link.txt --verbose=1
/usr/bin/g++    -D_HAS_CXX11_FLAG    CMakeFiles/cmTryCompileExec661944226.dir/src.cxx.o  -o cmTryCompileExec661944226 -rdynamic
make[1]: Leaving directory `/home/luwentao/software/STAT/3-Dyninst/build/CMakeFiles/CMakeTmp'

Source file was:
int main() { return 0;}
_____________________________________________________________________________________
 I do not konw where is wrong,can anyone help me?very thank you

**Comment by lee218llnl** [comment]
@buaaluwentao, which component is failing to build, is it Stackwalker/Dyninst? If so, you may need to report any build issues to the Dyninst project https://github.com/dyninst/dyninst. 

Also, you may have better luck installing STAT and all its dependences using Spack https://github.com/LLNL/spack/. I should get rid of that script-stat-install script. From STAT's "INSTALL" file:

59    STAT and its dependencies can also be built via the Spack 
60    package management tool, available at 
61    https://github.com/LLNL/spack. Running spack install stat 
62    should build STAT and all of its dependencies, including those 
63    require for the STAT GUI. Note that two Spack variants exist. 
64    The first is +examples, to enable building example MPI code 
65    that STAT can be tested against. This is disabled by default to 
66    avoid requiring an MPI library, but enabling it will trigger a 
67    build of MPI. The second is +dysect to enable building of the 
68    DySectAPI.

**Comment by lee218llnl** [comment]
@buaaluwentao Since this issue is quite old and I haven't heard back from you, I will close it for now. I still suggest the Spack installation method. If you still encounter issues building, please feel free to reopen this issue or create a new one.
