### ISSUE TITLE
Linking Problem - Boost

### ISSUE THREAD

**Issue by MichaelLettrich** [LLNL/STAT#9]
I am trying to compile and install STAT for the first time. Unfortunately I am having troubles with the compilation process. 

I have installed all dependencies on CentOS 7  (mostly from boost::system::generic_category()source, boost and libdwarf from the package manager).
I configured with 
```
./configure\
--prefix=$MYDIR \
--with-launchmon=/opt/stat/deps/LaunchMON \
--with-mrnet=/opt/stat/deps/mrnet-5.0.1 \
--with-stackwalker=/opt/stat/deps/dyninst-9.3.2
```
which runs without problems. However during linking I get undefined references to `boost::system::generic_category()`  inside  `mrnet-5.0.1/lib/libmrnet.a`. Nevertheless, unittests in mrnet work fine.

 For further details see attached log files. 

Any Help with that? 
Thanks in advance.

[configure.txt](https://github.com/LLNL/STAT/files/1208797/configure.txt)
[make.txt](https://github.com/LLNL/STAT/files/1208798/make.txt)

**Comment by lee218llnl** [comment]
Did you build MRNet with the --enable-shared configure flag? STAT should be linking to the .so of MRNet, which in theory should point to the appropriate boost libraries. Note that MRNet also has a --with-boost= flag if MRNet is not using the appropriate one.

I will point out that an alternative to build STAT and all its dependences is using Spack. Please refer to https://github.com/LLNL/STAT/blob/develop/INSTALL for more info.

**Comment by MichaelLettrich** [comment]
Thank you for your fast response and pointing me at the source of my problem. STAT now works like a charm.
